//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Contactos = new HashSet<Contactos>();
            this.Ofertas = new HashSet<Ofertas>();
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int id_cliente { get; set; }
        public string pais { get; set; }
        public string web { get; set; }
        public string fax { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Contactos> Contactos { get; set; }
        public virtual ICollection<Ofertas> Ofertas { get; set; }
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
