//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int id_comentario { get; set; }
        public Nullable<int> texto { get; set; }
        public Nullable<int> id_etapa_tarea { get; set; }
    
        public virtual Etapa_Tarea Etapa_Tarea { get; set; }
    }
}
