//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa_Tarea
    {
        public Etapa_Tarea()
        {
            this.Comentarios = new HashSet<Comentarios>();
        }
    
        public int id_etapa_tarea { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tarea { get; set; }
        public Nullable<int> id_etapa { get; set; }
    
        public virtual Etapas Etapas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual Tareas Tareas { get; set; }
    }
}
