//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISCOPEntities : DbContext
    {
        public SISCOPEntities()
            : base("name=SISCOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Contactos> Contactos { get; set; }
        public DbSet<Estados_Proyectos> Estados_Proyectos { get; set; }
        public DbSet<Etapa_Tarea> Etapa_Tarea { get; set; }
        public DbSet<Etapas> Etapas { get; set; }
        public DbSet<Proyecto_Usuario> Proyecto_Usuario { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Responsables> Responsables { get; set; }
        public DbSet<Estados_Ofertas> Estados_Ofertas { get; set; }
        public DbSet<Ofertas> Ofertas { get; set; }
        public DbSet<Proyectos> Proyectos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Comentarios> Comentarios { get; set; }
        public DbSet<Tareas> Tareas { get; set; }
    }
}
