//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prioridad_Etapa
    {
        public Prioridad_Etapa()
        {
            this.Tareas = new HashSet<Tareas>();
        }
    
        public int id_prioridad { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Tareas> Tareas { get; set; }
    }
}
