//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Etapa_Tarea = new HashSet<Etapa_Tarea>();
            this.Proyecto_Usuario = new HashSet<Proyecto_Usuario>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<Etapa_Tarea> Etapa_Tarea { get; set; }
        public virtual ICollection<Proyecto_Usuario> Proyecto_Usuario { get; set; }
    }
}
