//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa_Tarea
    {
        public int id_etapa_tarea { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tarea { get; set; }
        public Nullable<int> id_etapa { get; set; }
    
        public virtual Etapa Etapa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
