//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapa
    {
        public Etapa()
        {
            this.Etapa_Tarea = new HashSet<Etapa_Tarea>();
        }
    
        public int id_etapa { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public string fecha_inicio { get; set; }
        public string fecha_final { get; set; }
        public string estado { get; set; }
        public string encargado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Etapa_Tarea> Etapa_Tarea { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
