//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISCOPEntities : DbContext
    {
        public SISCOPEntities()
            : base("name=SISCOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Contacto> Contactos { get; set; }
        public DbSet<Etapa_Tarea> Etapa_Tarea { get; set; }
        public DbSet<Etapa> Etapas { get; set; }
        public DbSet<Oferta> Ofertas { get; set; }
        public DbSet<Ofertas_Contactos> Ofertas_Contactos { get; set; }
        public DbSet<Proyecto_Contactos> Proyecto_Contactos { get; set; }
        public DbSet<Proyecto_Usuario> Proyecto_Usuario { get; set; }
        public DbSet<Proyecto> Proyectos { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tarea> Tareas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
