//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public Oferta()
        {
            this.Ofertas_Contactos = new HashSet<Ofertas_Contactos>();
            this.Proyectos = new HashSet<Proyecto>();
        }
    
        public int id_oferta { get; set; }
        public string descripcion { get; set; }
        public string responsable { get; set; }
        public string anho { get; set; }
        public string pais { get; set; }
        public string fecha_recepcion { get; set; }
        public string fecha_presentacion { get; set; }
        public string estado { get; set; }
        public string nota { get; set; }
        public string observacion { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Ofertas_Contactos> Ofertas_Contactos { get; set; }
        public virtual ICollection<Proyecto> Proyectos { get; set; }
    }
}
