//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Ofertas = new HashSet<Oferta>();
            this.Proyectos = new HashSet<Proyecto>();
        }
    
        public int id_cliente { get; set; }
        public string pais { get; set; }
        public string web { get; set; }
        public string fax { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Oferta> Ofertas { get; set; }
        public virtual ICollection<Proyecto> Proyectos { get; set; }
    }
}
