//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public Contacto()
        {
            this.Ofertas_Contactos = new HashSet<Ofertas_Contactos>();
            this.Proyecto_Contactos = new HashSet<Proyecto_Contactos>();
        }
    
        public int id_contacto { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string pais { get; set; }
        public string nombre { get; set; }
        public string ocupacion { get; set; }
        public string telefonos { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<Ofertas_Contactos> Ofertas_Contactos { get; set; }
        public virtual ICollection<Proyecto_Contactos> Proyecto_Contactos { get; set; }
    }
}
