//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_Contactos
    {
        public string id_proyecto_contactos { get; set; }
        public Nullable<int> id_contacto { get; set; }
        public Nullable<int> id_proyecto { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
